"""AST types and standins (for `isinstance()` use)."""

import sys

from ast import (
    AST,
    Add,
    And,
    AnnAssign,
    Assert,
    Assign,
    AsyncFor,
    AsyncFunctionDef,
    AsyncWith,
    Attribute,
    AugAssign,
    Await,
    BinOp,
    BitAnd,
    BitOr,
    BitXor,
    BoolOp,
    Break,
    Call,
    ClassDef,
    Compare,
    Constant,
    Continue,
    Del,
    Delete,
    Dict,
    DictComp,
    Div,
    Eq,
    ExceptHandler,
    Expr,
    Expression,
    FloorDiv,
    For,
    FormattedValue,
    FunctionDef,
    FunctionType,
    GeneratorExp,
    Global,
    Gt,
    GtE,
    If,
    IfExp,
    Import,
    ImportFrom,
    In,
    Interactive,
    Invert,
    Is,
    IsNot,
    JoinedStr,
    LShift,
    Lambda,
    List,
    ListComp,
    Load,
    Lt,
    LtE,
    MatMult,
    Match,
    MatchAs,
    MatchClass,
    MatchMapping,
    MatchOr,
    MatchSequence,
    MatchSingleton,
    MatchStar,
    MatchValue,
    Mod,
    Module,
    Mult,
    Name,
    NamedExpr,
    Nonlocal,
    Not,
    NotEq,
    NotIn,
    Or,
    Pass,
    Pow,
    RShift,
    Raise,
    Return,
    Set,
    SetComp,
    Slice,
    Starred,
    Store,
    Sub,
    Subscript,
    Try,
    Tuple,
    TypeIgnore,
    UAdd,
    USub,
    UnaryOp,
    While,
    With,
    Yield,
    YieldFrom,
    alias,
    arg,
    arguments,
    boolop,
    cmpop,
    comprehension,
    excepthandler,
    expr,
    expr_context,
    keyword,
    match_case,
    mod,
    operator,
    pattern,
    stmt,
    type_ignore,
    unaryop,
    withitem,
)

if sys.version_info[:2] >= (3, 11):  # for isinstance() checks
    from ast import TryStar

else:
    class TryStar(AST): """Standin.""" ; pass  # should we try to duplicate params? opening up possible can of descent into madness there

if sys.version_info[:2] >= (3, 12):
    from ast import TypeAlias, type_param, TypeVar, ParamSpec, TypeVarTuple

else:
    class TypeAlias(AST): """Standin.""" ; pass
    class type_param(AST): """Standin.""" ; pass
    class TypeVar(AST): """Standin.""" ; pass
    class ParamSpec(AST): """Standin.""" ; pass
    class TypeVarTuple(AST): """Standin.""" ; pass

if sys.version_info[:2] >= (3, 14):
    from ast import TemplateStr, Interpolation

else:
    class TemplateStr(AST): """Standin.""" ; pass
    class Interpolation(AST): """Standin.""" ; pass

__all__ = [
    'AST',
    'Add',
    'And',
    'AnnAssign',
    'Assert',
    'Assign',
    'AsyncFor',
    'AsyncFunctionDef',
    'AsyncWith',
    'Attribute',
    'AugAssign',
    'Await',
    'BinOp',
    'BitAnd',
    'BitOr',
    'BitXor',
    'BoolOp',
    'Break',
    'Call',
    'ClassDef',
    'Compare',
    'Constant',
    'Continue',
    'Del',
    'Delete',
    'Dict',
    'DictComp',
    'Div',
    'Eq',
    'ExceptHandler',
    'Expr',
    'Expression',
    'FloorDiv',
    'For',
    'FormattedValue',
    'FunctionDef',
    'FunctionType',
    'GeneratorExp',
    'Global',
    'Gt',
    'GtE',
    'If',
    'IfExp',
    'Import',
    'ImportFrom',
    'In',
    'Interactive',
    'Invert',
    'Is',
    'IsNot',
    'JoinedStr',
    'LShift',
    'Lambda',
    'List',
    'ListComp',
    'Load',
    'Lt',
    'LtE',
    'MatMult',
    'Match',
    'MatchAs',
    'MatchClass',
    'MatchMapping',
    'MatchOr',
    'MatchSequence',
    'MatchSingleton',
    'MatchStar',
    'MatchValue',
    'Mod',
    'Module',
    'Mult',
    'Name',
    'NamedExpr',
    'Nonlocal',
    'Not',
    'NotEq',
    'NotIn',
    'Or',
    'Pass',
    'Pow',
    'RShift',
    'Raise',
    'Return',
    'Set',
    'SetComp',
    'Slice',
    'Starred',
    'Store',
    'Sub',
    'Subscript',
    'Try',
    'Tuple',
    'TypeIgnore',
    'UAdd',
    'USub',
    'UnaryOp',
    'While',
    'With',
    'Yield',
    'YieldFrom',
    'alias',
    'arg',
    'arguments',
    'boolop',
    'cmpop',
    'comprehension',
    'excepthandler',
    'expr',
    'expr_context',
    'keyword',
    'match_case',
    'mod',
    'operator',
    'pattern',
    'stmt',
    'type_ignore',
    'unaryop',
    'withitem',

    'TryStar',

    'TypeAlias',
    'type_param',
    'TypeVar',
    'ParamSpec',
    'TypeVarTuple',

    'TemplateStr',
    'Interpolation',
]
