#!/usr/bin/env python

TOS = [
    ('stmt', {}),
    ('stmts', {}),
    ('expr', {}),
    ('expr_all', {}),
    ('expr_arglike', {}),
    ('expr_slice', {}),
    ('Tuple_elt', {}),
    ('Tuple', {}),
    ('_Assign_targets', {}),
    ('_decorator_list', {}),
    ('_arglike', {}),
    ('_arglikes', {}),
    ('_comprehension_ifs', {}),
    ('arguments', {}),
    ('arg', {}),
    ('alias', {}),
    ('_aliases', {}),
    ('Import_name', {}),
    ('_Import_names', {}),
    ('ImportFrom_name', {}),
    ('_ImportFrom_names', {}),
    ('withitem', {}),
    ('_withitems', {}),
    ('pattern', {}),
    ('_pattern_attrlikes', {}),
    ('type_param', {'_ver': 12}),
    ('_type_params', {'_ver': 12}),
    ('_expr_arglikes', {'_verify': False}),
]

FROMS = [
    ('Module', {}, r'a'),
    ('Interactive', {}, r'a'),
    ('Expression', {}, r'a'),
    ('Expr', {}, r'a'),
    ('_Assign_targets', {}, r'a ='),
    ('_Assign_targets', {}, r'a = b ='),
    ('_decorator_list', {}, r'@a'),
    ('_decorator_list', {}, '@a\n@b'),
    ('_arglikes', {}, r'a'),
    ('_arglikes', {}, r'*b'),
    ('_arglikes', {}, r'b=c'),
    ('_arglikes', {}, r'**b'),
    ('_arglikes', {}, r'a, b'),
    ('_arglikes', {}, r'a, *b'),
    ('_arglikes', {}, r'a, b=c'),
    ('_arglikes', {}, r'a, **b'),
    ('expr_arglike', {}, r'*not a'),
    ('expr_slice', {}, r'a:b, c:d'),
    ('NamedExpr', {}, r'a := b'),
    ('BinOp', {}, r'a + b'),
    ('UnaryOp', {}, r'-a'),
    ('IfExp', {}, r'a if b else c'),
    ('Dict', {}, r'{a: b}'),
    ('Yield', {}, r'yield a'),
    ('YieldFrom', {}, r'yield from a'),
    ('Set', {}, r'{a}'),
    ('Set', {}, r'{a, b}'),
    ('Set', {}, r'{a, *b}'),
    ('Call', {}, r'a()'),
    ('Constant', {}, r'1'),
    ('Attribute', {}, r'a.b'),
    ('Starred', {}, r'*a'),
    ('Name', {}, r'a'),
    ('List', {}, r'[a]'),
    ('List', {}, r'[a, b]'),
    ('List', {}, r'[a, *b]'),
    ('Tuple', {}, r'a,'),
    ('Tuple', {}, r'a, b'),
    ('Tuple', {}, r'a, *b'),
    ('Slice', {}, r'a:b:c'),
    ('_comprehension_ifs', {}, r'if a'),
    ('_comprehension_ifs', {}, r'if a if b'),
    ('arguments', {}, r'a'),
    ('arguments', {}, r'*b'),
    ('arguments', {}, r'b=c'),
    ('arguments', {}, r'**b'),
    ('arguments', {}, r'a, b'),
    ('arguments', {}, r'a, *b'),
    ('arguments', {}, r'a, b=c'),
    ('arguments', {}, r'a, **b'),
    ('arguments', {}, r'a, /'),
    ('arguments', {}, r'*, a'),
    ('arg', {}, r'a'),
    ('arg', {}, r'a: int'),
    ('alias', {}, r'a'),
    ('alias', {}, r'a as b'),
    ('_aliases', {}, r'a'),
    ('_aliases', {}, r'a, b'),
    ('_aliases', {}, r'a, b as c'),
    ('withitem', {}, r'a'),
    ('withitem', {}, r'a as b'),
    ('_withitems', {}, r'a'),
    ('_withitems', {}, r'a, b'),
    ('_withitems', {}, r'a, b as c'),
    ('MatchValue', {}, r'1'),
    ('MatchSingleton', {}, r'True'),
    ('MatchSequence', {}, r'[a]'),
    ('MatchMapping', {}, r'{1: a}'),
    ('MatchClass', {}, r'a()'),
    ('MatchStar', {}, r'*a'),
    ('MatchAs', {}, r'a'),
    ('MatchOr', {}, r'a | b'),
    ('_pattern_attrlikes', {}, r'a'),
    ('_pattern_attrlikes', {}, r'b=c'),
    ('_pattern_attrlikes', {}, r'a, b'),
    ('_pattern_attrlikes', {}, r'a, b=c'),
    ('TypeVar', {'_ver': 12}, r'a'),
    ('TypeVar', {'_ver': 13}, r'a=b'),
    ('TypeVar', {'_ver': 12}, r'a: int'),
    ('TypeVar', {'_ver': 13}, r'a: int = b'),
    ('ParamSpec', {'_ver': 12}, r'**a'),
    ('TypeVarTuple', {'_ver': 12}, r'*a'),
    ('_type_params', {'_ver': 12}, r'a'),
    ('_type_params', {'_ver': 12}, r'a, *b'),
    ('_type_params', {'_ver': 12}, r'a, *b, **c'),
]


def main():
    for to_name, to_opts in TOS:
        print(f"'matrix_{to_name}': [  # ................................................................................")

        for from_name, from_opts, from_src in FROMS:
            if to_name == 'expr_slice' and from_name == 'MatchStar':
                from_opts = {'_ver': 11}

            print(f"\n('', 0, 0, '{to_name}', { {**from_opts, **to_opts} }, ('{from_name}', {from_src!r}),),")

        print(f"],\n")


if __name__ == '__main__':
    main()
