#!/usr/bin/env python

TOS = [
    ('stmt', {}),
    ('stmts', {}),
    ('expr', {}),
    ('expr_all', {}),
    ('expr_arglike', {}),
    ('expr_slice', {}),
    ('Tuple_elt', {}),
    ('Tuple', {}),
    ('_Assign_targets', {}),
    ('_decorator_list', {}),
    ('_arglike', {}),
    ('_arglikes', {}),
    ('_comprehension_ifs', {}),
    ('arguments', {}),
    ('arg', {}),
    ('alias', {}),
    ('_aliases', {}),
    ('Import_name', {}),
    ('_Import_names', {}),
    ('ImportFrom_name', {}),
    ('_ImportFrom_names', {}),
    ('withitem', {}),
    ('_withitems', {}),
    ('pattern', {}),
    ('_pattern_attrlikes', {}),
    ('type_param', {'_ver': 12}),
    ('_type_params', {'_ver': 12}),
    ('_expr_arglikes', {'_verify': False}),
]

FROMS = [
    ('Module', {}, 'a'),
    ('Interactive', {}, 'a'),
    ('Expression', {}, 'a'),
    ('Expr', {}, 'a'),
    ('_Assign_targets', {}, 'a ='),
    ('_Assign_targets', {}, 'a = b ='),
    ('_decorator_list', {}, '@a'),
    ('_decorator_list', {}, '@a\n@b'),
    ('_arglikes', {}, 'a'),
    ('_arglikes', {}, '*b'),
    ('_arglikes', {}, 'b=c'),
    ('_arglikes', {}, '**b'),
    ('_arglikes', {}, 'a, b'),
    ('_arglikes', {}, 'a, *b'),
    ('_arglikes', {}, 'a, b=c'),
    ('_arglikes', {}, 'a, **b'),
    ('expr_arglike', {}, '*not a'),
    ('expr_slice', {}, 'a:b, c:d'),
    ('NamedExpr', {}, 'a := b'),
    ('BinOp', {}, 'a + b'),
    ('UnaryOp', {}, '-a'),
    ('IfExp', {}, 'a if b else c'),
    ('Dict', {}, '{a: b}'),
    ('Yield', {}, 'yield a'),
    ('YieldFrom', {}, 'yield from a'),
    ('Set', {}, '{a}'),
    ('Set', {}, '{a, b}'),
    ('Set', {}, '{a, *b}'),
    ('Call', {}, 'a()'),
    ('Constant', {}, '1'),
    ('Attribute', {}, 'a.b'),
    ('Starred', {}, '*a'),
    ('Name', {}, 'a'),
    ('List', {}, '[a]'),
    ('List', {}, '[a, b]'),
    ('List', {}, '[a, *b]'),
    ('Tuple', {}, 'a,'),
    ('Tuple', {}, 'a, b'),
    ('Tuple', {}, 'a, *b'),
    ('Slice', {}, 'a:b:c'),
    ('_comprehension_ifs', {}, 'if a'),
    ('_comprehension_ifs', {}, 'if a if b'),
    ('arguments', {}, 'a'),
    ('arguments', {}, '*b'),
    ('arguments', {}, 'b=c'),
    ('arguments', {}, '**b'),
    ('arguments', {}, 'a, b'),
    ('arguments', {}, 'a, *b'),
    ('arguments', {}, 'a, b=c'),
    ('arguments', {}, 'a, **b'),
    ('arguments', {}, 'a, /'),
    ('arguments', {}, '*, a'),
    ('arguments', {}, 'a: int'),
    ('arguments', {}, 'a: int = b'),
    ('arg', {}, 'a'),
    ('arg', {}, 'a: int'),
    ('keyword', {}, 'a=b'),
    ('keyword', {}, '**b'),
    ('alias', {}, 'a'),
    ('alias', {}, 'a as b'),
    ('_aliases', {}, 'a'),
    ('_aliases', {}, 'a, b'),
    ('_aliases', {}, 'a, b as c'),
    ('withitem', {}, 'a'),
    ('withitem', {}, 'a as b'),
    ('_withitems', {}, 'a'),
    ('_withitems', {}, 'a, b'),
    ('_withitems', {}, 'a, b as c'),
    ('MatchValue', {}, '1'),
    ('MatchSingleton', {}, 'True'),
    ('MatchSequence', {}, '[a]'),
    ('MatchMapping', {}, '{1: a}'),
    ('MatchClass', {}, 'a()'),
    ('MatchStar', {}, '*a'),
    ('MatchAs', {}, 'a'),
    ('MatchOr', {}, 'a | b'),
    ('_pattern_attrlikes', {}, 'a'),
    ('_pattern_attrlikes', {}, 'b=c'),
    ('_pattern_attrlikes', {}, 'a, b'),
    ('_pattern_attrlikes', {}, 'a, b=c'),
    ('TypeVar', {'_ver': 12}, 'a'),
    ('TypeVar', {'_ver': 13}, 'a=b'),
    ('TypeVar', {'_ver': 12}, 'a: int'),
    ('TypeVar', {'_ver': 13}, 'a: int = b'),
    ('ParamSpec', {'_ver': 12}, '**a'),
    ('ParamSpec', {'_ver': 13}, '**a=b'),
    ('TypeVarTuple', {'_ver': 12}, '*a'),
    ('TypeVarTuple', {'_ver': 13}, '*a=b'),
    ('_type_params', {'_ver': 12}, 'a'),
    ('_type_params', {'_ver': 12}, 'a, b'),
    ('_type_params', {'_ver': 12}, 'a, *b'),
    ('_type_params', {'_ver': 12}, 'a, **b'),
    ('_type_params', {'_ver': 12}, 'a, *b, **c'),
    ('_type_params', {'_ver': 12}, 'a: int'),
    ('_type_params', {'_ver': 12}, 'a: int, b: float'),
    ('_type_params', {'_ver': 13}, 'a=c, b=d'),
    ('_type_params', {'_ver': 13}, 'a: int = c, b: float = d'),
    ('_expr_arglikes', {'_verify': False}, 'a'),
    ('_expr_arglikes', {'_verify': False}, '*b'),
    ('_expr_arglikes', {'_verify': False}, 'a, b'),
    ('_expr_arglikes', {'_verify': False}, 'a, *b'),
]


def main():
    for to_name, to_opts in TOS:
        print(f"'matrix_{to_name}': [  # ................................................................................")

        for from_name, from_opts, from_src in FROMS:
            if to_name == 'expr_slice' and from_name == 'MatchStar':
                from_opts = {'_ver': 11}

            print(f"\n('', 0, 0, '{to_name}', { {**to_opts, **from_opts} }, ('{from_name}', {from_src!r}),),")

        print(f"],\n")


if __name__ == '__main__':
    main()
